"""
Futures and Options Definitions

Contains TradFi venue mappings for Databento symbols covering:
- CME futures and options (equity indices, commodities, currencies, treasuries)
- ICE futures (agricultural, energy, currency indices)
"""

# TRADFI venue mappings - Databento symbols to venues/datasets (Issue #90)
TRADFI_VENUE_MAPPINGS: list[dict[str, str | None]] = [
    {
        "symbol": "ES.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "ES",
    },
    {
        "symbol": "NQ.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NASDAQ100",
        "code": "NQ",
    },
    {
        "symbol": "RTY.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "RUSSELL2000",
        "code": "RTY",
    },
    {
        "symbol": "YM.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "DOW",
        "code": "YM",
    },
    {
        "symbol": "CL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CRUDE",
        "code": "CL",
    },
    {
        "symbol": "NG.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NATGAS",
        "code": "NG",
    },
    {
        "symbol": "RB.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GASOLINE",
        "code": "RB",
    },
    {
        "symbol": "HO.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "HEATINGOIL",
        "code": "HO",
    },
    {
        "symbol": "GC.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GOLD",
        "code": "GC",
    },
    {
        "symbol": "SI.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SILVER",
        "code": "SI",
    },
    {
        "symbol": "HG.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "COPPER",
        "code": "HG",
    },
    {
        "symbol": "PL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "PLATINUM",
        "code": "PL",
    },
    {
        "symbol": "ZC.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CORN",
        "code": "ZC",
    },
    {
        "symbol": "ZW.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "WHEAT",
        "code": "ZW",
    },
    {
        "symbol": "ZS.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYBEAN",
        "code": "ZS",
    },
    {
        "symbol": "ZM.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYMEAL",
        "code": "ZM",
    },
    {
        "symbol": "ZL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYOIL",
        "code": "ZL",
    },
    {
        "symbol": "ZB.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TBOND",
        "code": "ZB",
    },
    {
        "symbol": "ZN.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE10Y",
        "code": "ZN",
    },
    {
        "symbol": "ZF.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE5Y",
        "code": "ZF",
    },
    {
        "symbol": "ZT.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE2Y",
        "code": "ZT",
    },
    {
        "symbol": "6E.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "EUR",
        "code": "6E",
    },
    {
        "symbol": "6J.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "JPY",
        "code": "6J",
    },
    {
        "symbol": "6B.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GBP",
        "code": "6B",
    },
    {
        "symbol": "6C.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CAD",
        "code": "6C",
    },
    {
        "symbol": "6A.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "AUD",
        "code": "6A",
    },
    {
        "symbol": "6S.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CHF",
        "code": "6S",
    },
    {
        "symbol": "6L.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "BRL",
        "code": "6L",
    },
    {
        "symbol": "6N.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NZD",
        "code": "6N",
    },
    {
        "symbol": "6Z.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "ZAR",
        "code": "6Z",
    },
    {
        "symbol": "6M.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "MXN",
        "code": "6M",
    },
    {
        "symbol": "ES.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "ES",
    },
    {
        "symbol": "NQ.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NASDAQ100",
        "code": "NQ",
    },
    {
        "symbol": "CL.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CRUDE",
        "code": "CL",
    },
    {
        "symbol": "GC.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GOLD",
        "code": "GC",
    },
    {
        "symbol": "EW1.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW1",
        "underlying": "ES",
    },
    {
        "symbol": "EW2.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW2",
        "underlying": "ES",
    },
    {
        "symbol": "EW3.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW3",
        "underlying": "ES",
    },
    {
        "symbol": "EW4.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW4",
        "underlying": "ES",
    },
    {
        "symbol": "CT.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COTTON",
        "code": "CT",
    },
    {
        "symbol": "CC.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COCOA",
        "code": "CC",
    },
    {
        "symbol": "KC.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COFFEE",
        "code": "KC",
    },
    {
        "symbol": "SB.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "SUGAR",
        "code": "SB",
    },
    {
        "symbol": "OJ.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "ORANGEJUICE",
        "code": "OJ",
    },
    {
        "symbol": "DX.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "DOLLARINDEX",
        "code": "DX",
    },
    {
        "symbol": "BRN.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "BRENT",
        "code": "BRN",
    },
    {
        "symbol": "G.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "GASOIL",
        "code": "G",
    },
    {
        "symbol": "T.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "WTI",
        "code": "T",
    },
]

# Backward-compatible alias (Issue #90)
TRADFI_INSTRUMENTS_CONFIG: list[dict[str, str | None]] = TRADFI_VENUE_MAPPINGS
