#!/usr/bin/env python3
# Epic: tradfi_master
# Lifecycle: oneoff
# Delete-when: after a fresh live read of prod/catalog.parquet (post rebuild-and-promote) shows
#   FUTURE/OPTION canonical_instrument_id AND EQUITY/ETF -USD suffix at ~100% (quarantine-only
#   residue enumerated), AND
#   plans/active/tradfi_manifest_content_recovery_completion_2026_07_24.md's "Migrate the
#   catalogue (Surface A)" P0 todo is flipped done.
"""Phase-B (Surface A) re-sweep — close the residual gap left after the 2026-07-18
``canonicalize_tradfi_catalogue_usd_lin_2026_07_18.py`` migration + its own
``instruments-service@1a73082e`` roll-up-filter durability fix
(``plans/archive/issues/tradfi_catalogue_rollup_ingests_sweep_bak_backups_2026_07_20.md``).

**Why a NEW script instead of re-running the 2026-07-18 one (both target the same
two surfaces, same shared primitive):**

1. **Live re-measurement (2026-07-25, this script's own scan, before any write) found the
   catalogue has DRIFTED BACK from the 2026-07-20 durability-fix's verified 99.84%/100% to
   98.86% FUTURE/OPTION (766,058/774,833) and 52.3% EQUITY/ETF ``-USD`` (698/1,334)** — NOT
   because the by_date sweep or the roll-up filter regressed (a live by_date sample across 12
   random days spanning 2020-2026 read 100% canonical for every CME/CBOE file), but because
   **ongoing forward writes keep appending NEW raw rows to the tail** of both surfaces:
   unresolvable FUTURE/OPTION product roots (the IS catalogue adapter's documented
   no-crash-no-fabricate fallback) and — confirmed live, index range 835,979-837,271, i.e. the
   newest rows — **bare (no ``-USD``) EQUITY snapshots**, because the IS per-day EQUITY writer
   was never routed through ``_build_tradfi_cash`` in the first place (A1's IS-catalogue-adapter
   fix only covers FUTURE/OPTION — see the still-open P1 todo "Route the tradfi writers through
   the shared build_canonical_instrument_id" in this workstream's plan). This script closes the
   CURRENT gap (a data migration); it does not fix the writer (that is the separate P1 todo —
   out of this script's scope, tracked so it doesn't silently re-drift forever).

2. **A live full-catalogue scan (2026-07-25) surfaced a real hazard the 2026-07-18 script does
   not guard against**: re-deriving via ``canonicalize_raw_tradfi_id`` for a row whose stored id
   ALREADY matches the target ``-USD@LIN`` shape sometimes returns a DIFFERENT value (63,476 of
   766,058 already-shape-canonical FUTURE rows, e.g. CME ``6AQ6`` raw -> stored
   ``…-20260817`` vs freshly-derived ``…-20260819`` — an expiry-date discrepancy, not a shape
   defect). Blindly rewriting on "primitive output != stored value" (the 2026-07-18 script's
   rule) would silently churn ~63K already-correct rows' VALUES on every re-run — a moving
   target, and outside THIS migration's mandate (id-SHAPE, not expiry-date-value correctness,
   which is a separate, undecided question flagged as a new P2 follow-up, not resolved here).
   **This script only ever rewrites a row whose CURRENT id does not already match the target
   shape** (see :func:`_already_canonical_shape`) — strictly narrower and idempotent: a row that
   is already shape-canonical is NEVER touched again, so re-running this script (or a future
   rebuild) cannot flip an already-correct id to a different value. This also makes the sweep
   dramatically cheaper (the expensive primitive call — ``classify_databento_symbol`` underneath
   — only runs for the small shape-non-canonical residue, not all ~775K rows every time),
   directly addressing the 2026-07-18 run's ``OSError(49 Can't assign requested address)``
   socket-exhaustion crash at ~83% through the by_date corpus (24 workers x ~2h of full-primitive
   calls on EVERY row). This script also processes the by_date sweep in bounded BATCHES (a fresh
   ``ThreadPoolExecutor`` per batch — see ``--batch-size``) so any per-batch socket/connection
   churn is released between batches instead of accumulating across the whole multi-hour run.

Both surfaces, same durability pattern as ``canonicalize_okx_margin_type_2026_07_09.py``:

1. ``prod/catalog.parquet`` (default target) — the rolled-up reference table. DURABILITY TRAP
   (proven twice now: the 2026-07-08 combo migration, and the 2026-07-20
   ``tradfi_catalogue_rollup_ingests_sweep_bak_backups_2026_07_20.md`` roll-up-filter defect): a
   ``prod/n``-only rewrite is REGENERATED by ``build_instrument_catalogue.py`` from the per-day
   ``instrument_availability/by_date/day=*/venue=*/instruments.parquet`` corpus, so a catalog-only
   fix silently reverts on the next scheduled roll-up.

2. ``instrument_availability/by_date/day=*/venue=*/instruments.parquet`` — the per-day-per-venue
   snapshots ``catalog.parquet`` is rolled up FROM. This script's id column here is
   ``instrument_key`` (not ``instrument_id``) with the same semantics.

Every row canonicalizes to exactly one status (never a silent fallback — see ``CanonStatus`` in
``tradfi_id_canonicalizer.py``): ``OK``/``ALREADY_CANONICAL`` shape-non-canonical rows get
``instrument_id``/``instrument_key`` and ``canonical_instrument_id`` rewritten byte-equal;
``instrument_type`` is NOT touched (live-confirmed 2026-07-25: already 100% UPPERCASE enum on
this surface — the earlier casing migration already landed and holds). Any
``QUARANTINE_*``/``NULL_OR_EMPTY`` row is left UNCHANGED and recorded in a quarantine sidecar
(bounded, counted by status + best-effort reason) — never force-parsed, never silently dropped.
A shape-already-canonical row is left UNCHANGED regardless of what the primitive would otherwise
propose (the durability-over-churn design decision above).

Usage::

    cd instruments-service

    # Dry-run against prod/catalog.parquet (default: report only, no GCS writes)
    .venv/bin/python scripts/canonicalize_tradfi_catalogue_usd_lin_2026_07_25.py

    # Dry-run fully offline against a local snapshot (zero GCS calls at all)
    .venv/bin/python scripts/canonicalize_tradfi_catalogue_usd_lin_2026_07_25.py \
        --local-catalog-snapshot /path/to/catalog.parquet

    # Full sweep of prod/catalog.parquet (backup + write + verify) — ORCHESTRATOR ONLY
    .venv/bin/python scripts/canonicalize_tradfi_catalogue_usd_lin_2026_07_25.py \
        --apply --full-sweep

    # Per-day corpus: bounded real smoke test (backup + write + verify each touched file)
    .venv/bin/python scripts/canonicalize_tradfi_catalogue_usd_lin_2026_07_25.py \
        --by-day --apply --by-day-sample 20

    # Per-day corpus: full real sweep, batched (recommended — avoids the 2026-07-18 socket
    # exhaustion by recreating the thread pool every --batch-size files)
    .venv/bin/python scripts/canonicalize_tradfi_catalogue_usd_lin_2026_07_25.py \
        --by-day --apply --by-day-full-sweep --workers 16 --batch-size 600

    # Per-day corpus: SHARDED full sweep (only needed on a multi-core box — the per-row
    # canonicalization is pure Python and therefore GIL-bound, so --workers alone saturates
    # ~1.3 cores no matter how high it is set; N separate PROCESSES over disjoint shards is the
    # only real speed-up). Mirrors market_tick_data_service.scripts.migrate_tradfi_canonical_2026_07.
    for i in $(seq 0 15); do
        .venv/bin/python scripts/canonicalize_tradfi_catalogue_usd_lin_2026_07_25.py \
            --by-day --apply --by-day-full-sweep --workers 8 --shard-of 16 --shard-index "$i" &
    done; wait

    # After BOTH surfaces are migrated, re-run the roll-up producer and re-verify prod/n stays
    # canonical (the actual durability proof — do not skip this step):
    .venv/bin/python scripts/build_instrument_catalogue.py --asset-group tradfi --mode full
    .venv/bin/python scripts/canonicalize_tradfi_catalogue_usd_lin_2026_07_25.py   # dry-run re-verify
"""

from __future__ import annotations

import argparse
import io
import json
import logging
import re
import time
from concurrent.futures import ThreadPoolExecutor, as_completed
from dataclasses import dataclass, field
from datetime import UTC, datetime

import pandas as pd
from unified_api_contracts import (
    TRADFI_CASH_TYPE_VALUES,
    assert_tradfi_derivative_ids_canonical,
    canonicalize_raw_tradfi_id,
)
from unified_trading_library import get_config, get_storage_client, resolve_bucket_name

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger(__name__)

CATALOG_FILENAME = "catalog.parquet"
BY_DATE_PREFIX = "instrument_availability/by_date/"

#: Same scope as the 2026-07-18 script — FUTURE/OPTION (id-shape) + the CASH quote-suffix types
#: (EQUITY/CURRENCY/ETF/BOND/COMMODITY/INDEX).
_DERIVATIVE_TYPES = ("FUTURE", "OPTION")
_TARGET_TYPES = _DERIVATIVE_TYPES + tuple(sorted(TRADFI_CASH_TYPE_VALUES))
_OK_STATUSES = ("OK", "ALREADY_CANONICAL")

_MAX_EXAMPLES = 6
_MAX_QUARANTINE_SAMPLE_PER_STATUS = 25

_UD_STRATEGY_RE = re.compile(r"^UD[_:]", re.IGNORECASE)
_NEGATIVE_STRIKE_RE = re.compile(r"[CP]-\d")

#: Target derivative id shape, mirrored from ``TARGET_TRADFI_DERIVATIVE_ID_RE``
#: (``unified_api_contracts.internal.reference.tradfi_id_canonicalizer`` — not re-exported
#: top-level) — used ONLY as a cheap pre-filter to decide whether a row needs the expensive
#: primitive call at all, never as a substitute for the primitive's own classification.
_CANONICAL_DERIVATIVE_RE = re.compile(r"^[A-Z0-9-]+:(FUTURE|OPTION):[A-Z0-9]+-USD@LIN-\d{8}(-\d+(\.\d+)?-[CP])?$")
#: Cash rows are canonical once they carry an explicit 3-letter quote suffix (every real tradfi
#: cash instrument today is USD-denominated per ``_build_tradfi_cash``, but this stays
#: quote-agnostic on purpose in case a non-USD quote is ever decided).
_CASH_SUFFIX_RE = re.compile(r"-[A-Z]{3}$")


def _already_canonical_shape(id_value: str, instrument_type: str) -> bool:
    """Cheap, vectorizable pre-filter: does ``id_value`` already look like the target shape for
    ``instrument_type``? Only rows failing this check are handed to the (expensive) shared
    primitive — see the module docstring's durability-over-churn rationale.
    """
    if instrument_type in _DERIVATIVE_TYPES:
        return bool(_CANONICAL_DERIVATIVE_RE.match(id_value))
    if instrument_type in TRADFI_CASH_TYPE_VALUES:
        return bool(_CASH_SUFFIX_RE.search(id_value))
    return False


def _bucket_name() -> str:
    return resolve_bucket_name(cloud="gcp", kind="instruments-store", asset_group="tradfi")


def _deployment_env() -> str:
    return get_config("DEPLOYMENT_ENV", "prod")


def _catalog_path(env: str) -> str:
    return f"{env}/{CATALOG_FILENAME}"


def _self_check() -> None:
    """Fixed regression self-checks — run unconditionally at the top of ``main()``
    (fail-loud if the shared primitive's behavior, or this script's shape pre-filter, ever
    drifts from what this migration assumes).
    """
    result = canonicalize_raw_tradfi_id(raw="E1AF0 C1600", venue="CME", instrument_type="OPTION")
    expected = "CME:OPTION:SP500-USD@LIN-20200117-1600-C"
    if result.status != "OK" or result.canonical_id != expected:
        msg = (
            "Self-check FAILED: canonicalize_raw_tradfi_id(raw='E1AF0 C1600', venue='CME', "
            f"instrument_type='OPTION') = {result!r}, expected canonical_id={expected!r}. "
            "Refusing to proceed — the shared primitive's behavior no longer matches this "
            "migration's assumptions."
        )
        raise AssertionError(msg)
    logger.info("Self-check PASSED: CME weekly option 'E1AF0 C1600' -> %s", expected)
    if _already_canonical_shape("E1AF0 C1600", "OPTION"):
        msg = "Self-check FAILED: the RAW input 'E1AF0 C1600' should NOT be pre-classified canonical."
        raise AssertionError(msg)
    if not _already_canonical_shape(expected, "OPTION"):
        msg = f"Self-check FAILED: the CANONICAL output {expected!r} should be recognized as already-canonical shape."
        raise AssertionError(msg)

    cash_result = canonicalize_raw_tradfi_id(raw="NASDAQ:EQUITY:AAPL", venue="NASDAQ", instrument_type="EQUITY")
    cash_expected = "NASDAQ:EQUITY:AAPL-USD"
    if cash_result.status != "OK" or cash_result.canonical_id != cash_expected:
        msg = (
            "Self-check FAILED (cash -USD): canonicalize_raw_tradfi_id(raw='NASDAQ:EQUITY:AAPL', "
            f"venue='NASDAQ', instrument_type='EQUITY') = {cash_result!r}, expected "
            f"canonical_id={cash_expected!r}."
        )
        raise AssertionError(msg)
    logger.info("Self-check PASSED: cash equity 'NASDAQ:EQUITY:AAPL' -> %s", cash_expected)

    # Durability-over-churn guard: an ALREADY shape-canonical id must be classified
    # already-canonical by the pre-filter regardless of what the primitive would derive fresh
    # (this is the whole point of the 2026-07-25 design change — see module docstring §2).
    if not _already_canonical_shape("CME:FUTURE:AUD-USD@LIN-20260817", "FUTURE"):
        msg = "Self-check FAILED: an already-shape-canonical FUTURE id was not recognized as such."
        raise AssertionError(msg)
    if _already_canonical_shape("NASDAQ:EQUITY:AAPL", "EQUITY"):
        msg = "Self-check FAILED: a bare (no quote suffix) EQUITY id was incorrectly classified canonical."
        raise AssertionError(msg)
    if _already_canonical_shape("CME:OPTION:LON0 C-100", "OPTION"):
        msg = "Self-check FAILED: a raw (space-containing) OPTION id was incorrectly classified canonical."
        raise AssertionError(msg)
    logger.info("Self-check PASSED: shape pre-filter correctly gates already-canonical vs raw ids.")


def _classify_quarantine_reason(status: str, raw: str, venue: str) -> str:
    """Best-effort human-readable bucket for the quarantine sidecar report only — NEVER used to
    decide the ``CanonStatus`` itself (that is the shared primitive's sole responsibility).
    """
    if status == "NULL_OR_EMPTY":
        return "null_or_empty"
    if status == "QUARANTINE_CONTINUOUS":
        return "continuous_root"
    if status == "QUARANTINE_COMBO":
        return "cboe_user_defined_strategy" if _UD_STRATEGY_RE.match(raw.strip()) else "combo_multi_leg"
    if status == "QUARANTINE_UNPARSEABLE":
        if _NEGATIVE_STRIKE_RE.search(raw):
            return "negative_strike"
        if venue.strip().upper() == "ICE":
            return "ice_qualifier_variant"
        return "other_unparseable"
    return "unknown"


@dataclass(slots=True)
class MigrationResult:
    """Result of :func:`_migrate_dataframe` — never a silent fallback per row."""

    df: pd.DataFrame
    status_counts: dict[str, int] = field(default_factory=dict)
    changed_idx: list[object] = field(default_factory=list)
    #: Rows whose ``instrument_type`` changed but whose id did NOT (a combo re-stamp) — these
    #: need to land in the write-set too even though they never touch ``id_col``.
    type_only_changed_idx: list[object] = field(default_factory=list)
    retype_count: int = 0
    #: Count of CASH (EQUITY/CURRENCY/ETF/BOND/COMMODITY/INDEX) rows whose id actually changed
    #: (picked up the quote suffix).
    cash_migrated_count: int = 0
    cash_examples: list[tuple[str, str]] = field(default_factory=list)
    #: Count of QUARANTINE_COMBO rows whose stored ``instrument_type`` got re-stamped to the
    #: UPPERCASE ``COMBO`` enum (id intentionally left unchanged — see module docstring).
    combo_restamp_count: int = 0
    #: True-derivative denominator/numerator computed from the CLASSIFIER-DERIVED type for the
    #: shape-non-canonical residue actually processed by the primitive (already-shape-canonical
    #: rows are counted separately below — see ``already_canonical_count``).
    derivative_total: int = 0
    derivative_ok: int = 0
    #: Rows that were ALREADY shape-canonical and therefore never sent to the primitive at all
    #: (the 2026-07-25 fast-path — see module docstring).
    already_canonical_count: int = 0
    #: EXACT count per "STATUS:reason" key — never sampled/bounded.
    quarantine_reason_counts: dict[str, int] = field(default_factory=dict)
    #: Bounded per-(status,reason) SAMPLE of raw ids — for the sidecar JSON only.
    quarantine_records: list[dict[str, str]] = field(default_factory=list)
    examples: list[tuple[str, str, str, str]] = field(default_factory=list)
    total_target_rows: int = 0


def _migrate_dataframe(df: pd.DataFrame, *, id_col: str, canonical_col: str) -> MigrationResult:
    """Recompute ``id_col``/``canonical_col`` for every FUTURE/OPTION/CASH row that is NOT
    already shape-canonical, via the shared ``canonicalize_raw_tradfi_id`` primitive.

    Works identically for BOTH surfaces — the catalogue (``id_col="instrument_id"``) and the
    per-day corpus (``id_col="instrument_key"``) — same primitive, same logic, only the id
    column name differs. Already-shape-canonical rows are SKIPPED ENTIRELY (never sent to the
    primitive, never rewritten) — see the module docstring's durability-over-churn rationale.
    Non-OK rows are left UNCHANGED in the returned ``df`` and recorded in ``quarantine_records``
    (never force-parsed, never silently dropped) — EXCEPT a ``QUARANTINE_COMBO`` row's
    ``instrument_type``, which IS re-stamped to the classifier-derived ``COMBO`` enum even
    though its id stays untouched.
    """
    if id_col not in df.columns or "instrument_type" not in df.columns or "venue" not in df.columns:
        return MigrationResult(df=df)

    target_mask = df["instrument_type"].isin(_TARGET_TYPES)
    target_idx_all = df.index[target_mask]
    result = MigrationResult(df=df.copy(), total_target_rows=len(target_idx_all))
    if len(target_idx_all) == 0:
        return result

    # Fast vectorized pre-filter: only rows whose CURRENT id does not already match the target
    # shape for their stored type go through the expensive per-row primitive call.
    already_ok = [
        _already_canonical_shape(str(df.at[idx, id_col]), str(df.at[idx, "instrument_type"])) for idx in target_idx_all
    ]
    result.already_canonical_count = sum(already_ok)
    target_idx = [idx for idx, ok in zip(target_idx_all, already_ok, strict=True) if not ok]

    has_raw_symbol_col = "raw_symbol" in df.columns
    has_underlying_col = "underlying" in df.columns
    has_canonical_col = canonical_col in df.columns
    _sample_counts_by_key: dict[str, int] = {}
    _example_keys_seen: set[str] = set()

    for idx in target_idx:
        row = result.df.loc[idx]
        stored_type = str(row["instrument_type"])
        venue = str(row["venue"])
        raw_symbol = row["raw_symbol"] if has_raw_symbol_col else None
        old_id = str(row[id_col])
        raw = str(raw_symbol) if raw_symbol is not None and str(raw_symbol).strip() else old_id

        canon = canonicalize_raw_tradfi_id(raw=raw, venue=venue, instrument_type=stored_type)
        result.status_counts[canon.status] = result.status_counts.get(canon.status, 0) + 1

        if canon.derived_instrument_type in _DERIVATIVE_TYPES:
            result.derivative_total += 1
            if canon.status in _OK_STATUSES:
                result.derivative_ok += 1

        if canon.status == "QUARANTINE_COMBO":
            reason = _classify_quarantine_reason(canon.status, raw, venue)
            reason_key = f"{canon.status}:{reason}"
            result.quarantine_reason_counts[reason_key] = result.quarantine_reason_counts.get(reason_key, 0) + 1
            sampled_for_key = _sample_counts_by_key.get(reason_key, 0)
            if sampled_for_key < _MAX_QUARANTINE_SAMPLE_PER_STATUS:
                _sample_counts_by_key[reason_key] = sampled_for_key + 1
                result.quarantine_records.append(
                    {"id": old_id, "venue": venue, "stored_type": stored_type, "status": canon.status, "reason": reason}
                )
            combo_type = (canon.derived_instrument_type or "COMBO").upper()
            if stored_type.upper() != combo_type:
                result.df.at[idx, "instrument_type"] = combo_type
                result.combo_restamp_count += 1
                result.retype_count += 1
                result.type_only_changed_idx.append(idx)
            continue

        if canon.status not in _OK_STATUSES or canon.canonical_id is None:
            reason = _classify_quarantine_reason(canon.status, raw, venue)
            reason_key = f"{canon.status}:{reason}"
            result.quarantine_reason_counts[reason_key] = result.quarantine_reason_counts.get(reason_key, 0) + 1
            sampled_for_key = _sample_counts_by_key.get(reason_key, 0)
            if sampled_for_key < _MAX_QUARANTINE_SAMPLE_PER_STATUS:
                _sample_counts_by_key[reason_key] = sampled_for_key + 1
                result.quarantine_records.append(
                    {"id": old_id, "venue": venue, "stored_type": stored_type, "status": canon.status, "reason": reason}
                )
            continue

        new_id = canon.canonical_id
        new_type = (canon.derived_instrument_type or stored_type).upper()
        is_cash = new_type in TRADFI_CASH_TYPE_VALUES
        if new_id != old_id:
            result.df.at[idx, id_col] = new_id
            result.changed_idx.append(idx)
            if is_cash:
                result.cash_migrated_count += 1
                if len(result.cash_examples) < _MAX_EXAMPLES:
                    result.cash_examples.append((old_id, new_id))
            example_key = f"{venue}:{stored_type}"
            if len(result.examples) < _MAX_EXAMPLES and example_key not in _example_keys_seen:
                _example_keys_seen.add(example_key)
                result.examples.append((old_id, new_id, stored_type, new_type))
        if has_canonical_col:
            result.df.at[idx, canonical_col] = new_id
        if has_underlying_col and canon.derived_underlying_human:
            result.df.at[idx, "underlying"] = canon.derived_underlying_human

    return result


def _report_dry_run(result: MigrationResult, *, source_label: str) -> None:
    total = result.total_target_rows
    processed = total - result.already_canonical_count
    ok = sum(result.status_counts.get(s, 0) for s in _OK_STATUSES)
    already_plus_ok = result.already_canonical_count + ok
    pct = 100.0 * already_plus_ok / max(1, total)
    logger.info("=== DRY-RUN report (%s, READ-ONLY, 0 writes) ===", source_label)
    logger.info("Total FUTURE/OPTION/CASH rows in scope (stored-type mask): %d", total)
    logger.info(
        "Already shape-canonical (skipped, not touched): %d; processed via primitive: %d",
        result.already_canonical_count,
        processed,
    )
    logger.info("Shape-canonical overall (already + fixed): %d / %d (%.4f%%)", already_plus_ok, total, pct)
    logger.info("Status distribution (processed subset only): %s", result.status_counts)
    logger.info("Quarantine breakdown (status:reason -> EXACT count): %s", result.quarantine_reason_counts)
    logger.info("CASH rows that would migrate to the quote-suffixed id (count): %d", result.cash_migrated_count)
    for old_id, new_id in result.cash_examples:
        logger.info("  [CASH] %r -> %r", old_id, new_id)
    logger.info("QUARANTINE_COMBO rows that would re-stamp instrument_type -> COMBO: %d", result.combo_restamp_count)
    logger.info("Before -> after examples (id, old_type -> new_type):")
    for old_id, new_id, old_t, new_t in result.examples:
        marker = "  [RETYPE]" if old_t != new_t else ""
        logger.info("  %r -> %r  (%s -> %s)%s", old_id, new_id, old_t, new_t, marker)


def _upload_json_report(bucket_name: str, path: str, payload: dict[str, object]) -> None:
    storage_client = get_storage_client()
    body = json.dumps(payload, indent=2, default=str).encode("utf-8")
    storage_client.upload_bytes(bucket_name, path, body)  # pyright: ignore[reportAttributeAccessIssue]
    logger.info("Quarantine sidecar report written: gs://%s/%s (%d bytes)", bucket_name, path, len(body))


# --------------------------------------------------------------------------- catalog.parquet ----


def _migrate_catalog(*, apply: bool, full_sweep: bool, sample_size: int, local_snapshot: str | None) -> int:
    if local_snapshot:
        if apply:
            logger.error("--local-catalog-snapshot is read-only-offline; refusing to combine with --apply.")
            return 1
        logger.info("Reading LOCAL offline snapshot: %s (zero GCS calls)", local_snapshot)
        df = pd.read_parquet(local_snapshot)
        source_label = f"local snapshot {local_snapshot}"
        logger.info("Loaded %s — %d total rows", source_label, len(df))
        result = _migrate_dataframe(df, id_col="instrument_id", canonical_col="canonical_instrument_id")
        _report_dry_run(result, source_label=source_label)
        logger.info("DRY-RUN (no writes). Re-run against real GCS with --apply --full-sweep to migrate prod.")
        return 0

    env = _deployment_env()
    bucket_name = _bucket_name()
    catalog_path = _catalog_path(env)

    storage_client = get_storage_client()
    raw = storage_client.download_bytes(bucket_name, catalog_path)  # pyright: ignore[reportAttributeAccessIssue]
    df = pd.read_parquet(io.BytesIO(raw))
    source_label = f"gs://{bucket_name}/{catalog_path}"
    logger.info("Loaded %s — %d total rows", source_label, len(df))

    result = _migrate_dataframe(df, id_col="instrument_id", canonical_col="canonical_instrument_id")

    if not apply:
        _report_dry_run(result, source_label=source_label)
        logger.info("DRY-RUN (no writes). Re-run with --apply --full-sweep to migrate all rows against prod.")
        return 0

    id_change_idx = result.changed_idx if full_sweep else result.changed_idx[:sample_size]
    write_idx = list(id_change_idx) + list(result.type_only_changed_idx)
    if not write_idx:
        logger.warning("Nothing to migrate — no writes performed.")
        return 0

    ts = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
    backup_path = f"{env}/backups/{CATALOG_FILENAME}.pre_usd_lin_resweep_{ts}.bak.parquet"
    storage_client.upload_bytes(bucket_name, backup_path, raw)  # pyright: ignore[reportAttributeAccessIssue]
    logger.info("Backup written: gs://%s/%s (%d bytes)", bucket_name, backup_path, len(raw))

    write_set = set(write_idx)
    out_df = df.copy()
    for idx in write_set:
        for col in ("instrument_id", "canonical_instrument_id", "instrument_type", "underlying"):
            if col in result.df.columns:
                out_df.at[idx, col] = result.df.at[idx, col]

    out = io.BytesIO()
    out_df.to_parquet(out, index=False, coerce_timestamps="us", allow_truncated_timestamps=True)
    storage_client.upload_bytes(bucket_name, catalog_path, out.getvalue())  # pyright: ignore[reportAttributeAccessIssue]
    logger.info(
        "APPLIED — %d row(s) migrated (%s), gs://%s/%s rewritten (%d bytes)",
        len(write_set),
        "full sweep" if full_sweep else f"bounded sample of {sample_size}",
        bucket_name,
        catalog_path,
        len(out.getvalue()),
    )

    quarantine_path = f"{env}/backups/{CATALOG_FILENAME}.pre_usd_lin_resweep_{ts}.quarantine.json"
    _upload_json_report(
        bucket_name,
        quarantine_path,
        {
            "generated_at": ts,
            "surface": "catalog.parquet",
            "already_canonical_count": result.already_canonical_count,
            "status_counts": result.status_counts,
            "cash_migrated_count": result.cash_migrated_count,
            "combo_restamp_count": result.combo_restamp_count,
            "quarantine_reason_counts": result.quarantine_reason_counts,
            "quarantine_sample": result.quarantine_records,
        },
    )

    verify_raw = storage_client.download_bytes(bucket_name, catalog_path)  # pyright: ignore[reportAttributeAccessIssue]
    verify_df = pd.read_parquet(io.BytesIO(verify_raw))
    verify_mask = verify_df["instrument_type"].isin(_TARGET_TYPES) | verify_df.index.isin(write_set)
    checked, canonical, violations = assert_tradfi_derivative_ids_canonical(
        verify_df.loc[verify_mask, "instrument_id"].astype(str).tolist(),
        verify_df.loc[verify_mask, "instrument_type"].astype(str).tolist(),
    )
    quarantined_ids = {rec["id"] for rec in result.quarantine_records}
    unexpected = [v for v in violations if not any(v.startswith(f"id={qid!r}") for qid in quarantined_ids)]
    logger.info(
        "Post-apply verify — checked=%d canonical=%d violations_sample=%d unexpected_new_violations=%d",
        checked,
        canonical,
        len(violations),
        len(unexpected),
    )
    if unexpected:
        logger.error("VERIFICATION found unexpected (non-quarantined) violations: %s", unexpected[:10])
        return 1
    logger.info("Verification PASSED.")
    return 0


# ------------------------------------------------------------------------------ per-day corpus ----


_MAX_VENUE_RESOLVE_DEPTH = 4


def _resolve_venue_dirs(bucket, prefix: str) -> list[str]:  # Bucket (avoid deep-import for type-only use)
    """BFS through delimited (non-recursive) listings from ``prefix`` until every branch reaches
    a ``venue=`` directory or :data:`_MAX_VENUE_RESOLVE_DEPTH` is exhausted. Handles both the
    current shallow ``day=*/venue=*/`` layout and the legacy nested layout.
    """
    resolved: list[str] = []
    frontier = [prefix]
    depth = 0
    while frontier and depth < _MAX_VENUE_RESOLVE_DEPTH:
        next_frontier: list[str] = []
        for p in frontier:
            it = bucket.list_blobs(prefix=p, delimiter="/")
            list(it)
            for child in sorted(it.prefixes):
                leaf = child.rstrip("/").rsplit("/", 1)[-1]
                if leaf.startswith("venue="):
                    resolved.append(child)
                else:
                    next_frontier.append(child)
        frontier = next_frontier
        depth += 1
    return resolved


def shard_slice(files: list[str], *, shard_of: int, shard_index: int) -> list[str]:
    """Return this process's disjoint slice of ``files`` (stride partition) — see the OKX/
    2026-07-18-script precedent for why striding beats contiguous blocks.
    """
    if shard_of < 1:
        raise ValueError(f"shard_of must be >= 1 (got {shard_of})")
    if not 0 <= shard_index < shard_of:
        raise ValueError(f"shard_index must satisfy 0 <= index < shard_of={shard_of} (got {shard_index})")
    return files[shard_index::shard_of]


def _list_by_date_files(
    storage_client, bucket_name: str
) -> list[str]:  # StorageClient (avoid deep-import for type-only use)
    """Enumerate every real ``instruments.parquet`` per-day-per-venue file via delimited
    (non-recursive) listing — ONE single walk, not a repeated/recursive corpus walk.
    """
    bucket = storage_client.bucket(bucket_name)
    it = bucket.list_blobs(prefix=BY_DATE_PREFIX, delimiter="/")
    list(it)
    day_prefixes = sorted(it.prefixes)
    logger.info("Real day partitions: %d", len(day_prefixes))

    def _check_day(day_prefix: str) -> list[str]:
        return [f"{venue_dir}instruments.parquet" for venue_dir in _resolve_venue_dirs(bucket, day_prefix)]

    files: list[str] = []
    with ThreadPoolExecutor(max_workers=40) as ex:
        futs = [ex.submit(_check_day, dp) for dp in day_prefixes]
        for fut in as_completed(futs):
            files.extend(fut.result())
    return files


@dataclass(slots=True)
class FileMigrationSummary:
    """Per-file result of :func:`_migrate_one_by_day_file` — typed so the by-day aggregation
    loop stays basedpyright-clean without ``# type: ignore``.
    """

    path: str
    rows_total: int = 0
    rows_in_scope: int = 0
    already_canonical_count: int = 0
    status_counts: dict[str, int] = field(default_factory=dict)
    changed_count: int = 0
    cash_migrated_count: int = 0
    combo_restamp_count: int = 0
    quarantine_reason_counts: dict[str, int] = field(default_factory=dict)
    quarantine_sample: list[dict[str, str]] = field(default_factory=list)
    wrote: bool = False
    error: str | None = None


def _migrate_one_by_day_file(  # StorageClient (avoid deep-import for type-only use)
    storage_client, bucket_name: str, path: str, *, apply: bool
) -> FileMigrationSummary:
    """Migrate (or, in dry-run, just analyze) one real per-day-per-venue snapshot file. Never
    raises on a single-file parse issue (shard-level failure isolation).
    """
    raw = storage_client.download_bytes(bucket_name, path)
    try:
        df = pd.read_parquet(io.BytesIO(raw))
    except (OSError, ValueError) as exc:
        return FileMigrationSummary(path=path, error=str(exc))

    if "instrument_key" not in df.columns:
        return FileMigrationSummary(path=path, rows_total=len(df))

    result = _migrate_dataframe(df, id_col="instrument_key", canonical_col="canonical_instrument_id")
    summary = FileMigrationSummary(
        path=path,
        rows_total=len(df),
        rows_in_scope=result.total_target_rows,
        already_canonical_count=result.already_canonical_count,
        status_counts=result.status_counts,
        changed_count=len(result.changed_idx),
        cash_migrated_count=result.cash_migrated_count,
        combo_restamp_count=result.combo_restamp_count,
        quarantine_reason_counts=result.quarantine_reason_counts,
        quarantine_sample=result.quarantine_records[:5],
    )

    if not apply or (not result.changed_idx and result.retype_count == 0):
        return summary

    ts = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
    backup_path = path.replace("instruments.parquet", f"instruments.usdlin.resweep.{ts}.bak.parquet")
    storage_client.upload_bytes(bucket_name, backup_path, raw)

    out = io.BytesIO()
    result.df.to_parquet(out, index=False, coerce_timestamps="us", allow_truncated_timestamps=True)
    storage_client.upload_bytes(bucket_name, path, out.getvalue())
    summary.wrote = True
    return summary


def _migrate_by_day(
    *,
    apply: bool,
    full_sweep: bool,
    sample_size: int,
    workers: int,
    batch_size: int,
    shard_of: int = 1,
    shard_index: int = 0,
) -> int:
    bucket_name = _bucket_name()
    storage_client = get_storage_client()
    files = _list_by_date_files(storage_client, bucket_name)
    logger.info("Real per-day-per-venue files found (single delimited listing): %d", len(files))

    scope = files if full_sweep else files[:sample_size]
    if shard_of > 1:
        before = len(scope)
        scope = shard_slice(scope, shard_of=shard_of, shard_index=shard_index)
        logger.info(
            "Shard %d/%d: %d of %d file(s) in this process's disjoint slice.",
            shard_index,
            shard_of,
            len(scope),
            before,
        )
    logger.info(
        "%s %d file(s) (%s) with %d workers, batch_size=%d...",
        "Migrating" if apply else "Analyzing (DRY-RUN, no writes)",
        len(scope),
        "full sweep" if full_sweep else f"bounded sample of {sample_size}",
        workers,
        batch_size,
    )

    t0 = time.time()
    n_scanned = 0
    n_touched = 0
    n_already_canonical = 0
    total_status_counts: dict[str, int] = {}
    total_cash_migrated = 0
    total_combo_restamp = 0
    total_reason_counts: dict[str, int] = {}
    all_quarantine: list[dict[str, str]] = []
    total_retype = 0

    # Batched: a fresh ThreadPoolExecutor per batch releases any per-batch socket/connection
    # churn instead of letting it accumulate across a multi-hour single pool (the 2026-07-18
    # run's OSError(49) socket-exhaustion crash at ~83% through the corpus with one long-lived
    # 24-worker pool).
    for batch_start in range(0, len(scope), max(1, batch_size)):
        batch = scope[batch_start : batch_start + batch_size]
        with ThreadPoolExecutor(max_workers=workers) as ex:
            futs = {
                ex.submit(_migrate_one_by_day_file, storage_client, bucket_name, path, apply=apply): path
                for path in batch
            }
            for fut in as_completed(futs):
                summary = fut.result()
                n_scanned += 1
                if summary.error:
                    logger.warning(
                        "  file %s failed to parse: %s (skipped, shard-isolated)", summary.path, summary.error
                    )
                for status, count in summary.status_counts.items():
                    total_status_counts[status] = total_status_counts.get(status, 0) + count
                for reason_key, count in summary.quarantine_reason_counts.items():
                    total_reason_counts[reason_key] = total_reason_counts.get(reason_key, 0) + count
                total_cash_migrated += summary.cash_migrated_count
                total_combo_restamp += summary.combo_restamp_count
                n_already_canonical += summary.already_canonical_count
                all_quarantine.extend(summary.quarantine_sample)
                if summary.combo_restamp_count:
                    total_retype += summary.combo_restamp_count
                if summary.wrote:
                    n_touched += 1
                if n_scanned % 200 == 0:
                    logger.info(
                        "  progress %d/%d files scanned, %d touched (t=%.1fs)",
                        n_scanned,
                        len(scope),
                        n_touched,
                        time.time() - t0,
                    )

    elapsed = time.time() - t0
    ok = sum(total_status_counts.get(s, 0) for s in _OK_STATUSES)
    processed = sum(total_status_counts.values())
    already_plus_ok = n_already_canonical + ok
    denom = n_already_canonical + processed
    logger.info(
        "%s — %d/%d file(s) %s, elapsed=%.1fs. already_canonical=%d processed=%d status_counts=%s "
        "shape_canonical=%d/%d (%.4f%%) combo_restamp=%d",
        "APPLIED" if apply else "DRY-RUN complete",
        n_touched if apply else n_scanned,
        len(scope),
        "touched" if apply else "scanned",
        elapsed,
        n_already_canonical,
        processed,
        total_status_counts,
        already_plus_ok,
        max(1, denom),
        100.0 * already_plus_ok / max(1, denom),
        total_combo_restamp,
    )
    logger.info("Quarantine breakdown (status:reason -> EXACT count): %s", total_reason_counts)
    logger.info("CASH rows migrated to the quote-suffixed id (count): %d", total_cash_migrated)

    if not apply:
        logger.info("Re-run with --apply --by-day-sample N (smoke test) or --by-day-full-sweep to write.")
        return 0

    ts = datetime.now(UTC).strftime("%Y%m%d-%H%M%S")
    env = _deployment_env()
    shard_suffix = "" if shard_of <= 1 else f"_shard{shard_index}of{shard_of}"
    quarantine_path = f"{env}/backups/by_date_usdlin_resweep_quarantine_{ts}{shard_suffix}.json"
    _upload_json_report(
        bucket_name,
        quarantine_path,
        {
            "generated_at": ts,
            "surface": "instrument_availability/by_date",
            "shard_of": shard_of,
            "shard_index": shard_index,
            "files_scanned": n_scanned,
            "files_touched": n_touched,
            "already_canonical_count": n_already_canonical,
            "status_counts": total_status_counts,
            "cash_migrated_count": total_cash_migrated,
            "combo_restamp_count": total_combo_restamp,
            "quarantine_reason_counts": total_reason_counts,
            "quarantine_sample": all_quarantine[: _MAX_QUARANTINE_SAMPLE_PER_STATUS * 4],
        },
    )
    logger.info(
        "IMPORTANT (durability): re-run build_instrument_catalogue.py --asset-group tradfi --mode full "
        "next, then re-verify prod/catalog.parquet stays canonical — a catalog-only fix silently reverts "
        "on the next scheduled roll-up otherwise."
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--apply", action="store_true", help="Write migrated data (default: dry-run/report only).")
    parser.add_argument("--full-sweep", action="store_true", help="prod/catalog.parquet: migrate ALL mismatched rows.")
    parser.add_argument("--sample-size", type=int, default=25, help="prod/catalog.parquet bounded sample size.")
    parser.add_argument(
        "--local-catalog-snapshot",
        type=str,
        default=None,
        help="Dry-run ONLY: read catalog.parquet from this local path instead of GCS (zero GCS calls at all).",
    )
    parser.add_argument(
        "--by-day",
        action="store_true",
        help="Target the per-day instrument_availability corpus instead of prod/catalog.parquet.",
    )
    parser.add_argument(
        "--by-day-sample", type=int, default=20, help="Per-day corpus bounded file count (dry-run or apply)."
    )
    parser.add_argument("--by-day-full-sweep", action="store_true", help="Per-day corpus: process ALL real files.")
    parser.add_argument("--workers", type=int, default=16, help="Thread-pool concurrency for per-day corpus ops.")
    parser.add_argument(
        "--batch-size",
        type=int,
        default=600,
        help="Per-day corpus: files per ThreadPoolExecutor batch (a fresh pool per batch avoids the "
        "2026-07-18 run's long-lived-pool socket exhaustion).",
    )
    parser.add_argument(
        "--shard-of",
        type=int,
        default=1,
        help="Total PROCESS shard count for the per-day sweep (default 1 = unsharded). See module docstring.",
    )
    parser.add_argument(
        "--shard-index", type=int, default=0, help="0-based index of THIS process's shard (see --shard-of)."
    )
    args = parser.parse_args()

    if args.shard_of < 1:
        parser.error("--shard-of must be >= 1")
    if not 0 <= args.shard_index < args.shard_of:
        parser.error(f"--shard-index must satisfy 0 <= index < --shard-of ({args.shard_of})")

    _self_check()

    if args.by_day:
        return _migrate_by_day(
            apply=args.apply,
            full_sweep=args.by_day_full_sweep,
            sample_size=args.by_day_sample,
            workers=args.workers,
            batch_size=args.batch_size,
            shard_of=args.shard_of,
            shard_index=args.shard_index,
        )
    return _migrate_catalog(
        apply=args.apply,
        full_sweep=args.full_sweep,
        sample_size=args.sample_size,
        local_snapshot=args.local_catalog_snapshot,
    )


if __name__ == "__main__":
    raise SystemExit(main())
