#!/usr/bin/env python3
# Epic: sports_master
# Lifecycle: campaign
# Delete-when: a recurring CLI subcommand owns WEATHER + PLAYER_VALUES coverage refresh
#   (the UAC registry JSON is then regenerated by that CLI, not this script).
"""Bootstrap the UAC WEATHER + PLAYER_VALUES league-coverage entries from provider knowledge.

Unlike the GCS-corpus-driven ``refresh_sports_league_entity_coverage_2026_06_21.py``
(which reads ``capture_status=captured`` rows), this script derives coverage from the
static provider mappings already in UAC:

- **WEATHER**: all leagues in ``SOCCER_FOOTBALL_INFO_IDS`` (33 leagues — these are the
  leagues for which the open_meteo adapter fetches fixture weather; the SFI ID is the
  key used to locate ground coordinates).
- **PLAYER_VALUES**: all leagues in ``TRANSFERMARKT_IDS`` (32 leagues — the Transfermarkt
  scraper covers exactly these leagues).

This is a *bootstrap* complement to the corpus refresh: use it when captured rows are
sparse (e.g. after a new deployment) or to seed the map before the corpus accumulates.
The corpus refresh should be run afterwards to pick up any additional leagues that have
actually produced captured rows.

``--write`` overwrites the UAC JSON in place (commit it via quickmerge in UAC);
default prints a diff vs the committed map.

Usage:
  .venv-workspace/bin/python \
    scripts/refresh_sports_weather_player_values_league_coverage_2026_06_21.py \
      [--write] [--uac-json <path>]
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

from unified_api_contracts.canonical.domain.sports.provider_league_ids import (
    SOCCER_FOOTBALL_INFO_IDS,
    TRANSFERMARKT_IDS,
)

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("refresh_weather_player_values_coverage")

_DEFAULT_UAC_JSON = (
    Path(__file__).resolve().parents[2]
    / "unified-api-contracts"
    / "unified_api_contracts"
    / "registry"
    / "data"
    / "sports_league_entity_coverage.json"
)


def build_provider_coverage() -> dict[str, list[str]]:
    """Return {ENTITY: sorted([LEAGUE_UPPER, ...])} from provider mappings."""
    return {
        "PLAYER_VALUES": sorted(TRANSFERMARKT_IDS.keys()),
        "WEATHER": sorted(SOCCER_FOOTBALL_INFO_IDS.keys()),
    }


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument(
        "--write",
        action="store_true",
        help="Merge provider coverage into the UAC JSON in place (then commit in UAC).",
    )
    p.add_argument(
        "--uac-json",
        type=Path,
        default=_DEFAULT_UAC_JSON,
        help="Path to the UAC coverage JSON.",
    )
    args = p.parse_args(argv)

    provider_map = build_provider_coverage()
    for entity, leagues in provider_map.items():
        logger.info("Provider coverage: %s -> %d leagues", entity, len(leagues))

    old_map: dict[str, list[str]] = {}
    if args.uac_json.exists():
        old_map = json.loads(args.uac_json.read_text())

    added = {e: sorted(set(provider_map[e]) - set(old_map.get(e, []))) for e in provider_map}
    added = {e: lg for e, lg in added.items() if lg}
    removed = {e: sorted(set(old_map.get(e, [])) - set(provider_map[e])) for e in provider_map}
    removed = {e: lg for e, lg in removed.items() if lg}

    if added:
        logger.info("Leagues to ADD vs committed map: %s", added)
    if removed:
        logger.info("Leagues to REMOVE vs committed map (kept unless --write): %s", removed)
    if not added and not removed:
        logger.info("No drift vs committed coverage map for WEATHER / PLAYER_VALUES.")

    if args.write:
        new_map = dict(old_map)
        for entity, leagues in provider_map.items():
            new_map[entity] = sorted(leagues)
        args.uac_json.write_text(json.dumps(new_map, indent=2, sort_keys=True) + "\n")
        logger.info("Wrote merged map -> %s (commit in UAC via quickmerge).", args.uac_json)
    else:
        logger.info("DRY RUN — committed UAC JSON untouched (use --write to overwrite).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
