#!/usr/bin/env python3
# Epic: sports_master
# Lifecycle: campaign
# Delete-when: a recurring CLI subcommand owns the observed (league x entity)
#   coverage refresh (the UAC registry JSON is then regenerated by that CLI, not this script).
"""Refresh the UAC observed (league x per-fixture-entity) coverage map from the
captured ``instruments-store-sports`` corpus.

The map ``unified_api_contracts/registry/data/sports_league_entity_coverage.json``
is DERIVED data: a ``(league, entity)`` pair is *covered* iff >=1 ``captured``
manifest row exists for it across history. This script scans the live sports
``_index`` ``capture_status=captured`` rows for the api_football enrichment
entities (PLAYER_STATS / FIXTURE_LINEUPS / FIXTURE_EVENTS / FIXTURE_STATS /
TEAMS / STANDINGS / INJURIES), groups by ``(data_type, league_id.upper())``,
and writes the ``{ENTITY: [LEAGUE, ...]}`` map. ``--write`` overwrites the UAC
JSON in place (commit it via quickmerge in UAC); default prints a diff vs the
committed map.

This keeps the registry honest as new (league, entity) cells start producing
captured rows (promotion/relegation, a league newly gaining API-Football
player-stats coverage). It is READ-ONLY against GCS — it never writes the
manifest. Pair with the Part-3 relabel migration
(``relabel_sports_no_provider_coverage_2026_06_21.py``) which CONSUMES the map.

Usage:
  GCP_PROJECT_ID=central-element-323112 PROJECT_ID=central-element-323112 DEPLOYMENT_ENV_SHORT=prd \
    .venv-workspace/bin/python scripts/refresh_sports_league_entity_coverage_2026_06_21.py \
      [--write] [--uac-json <path>]
"""

from __future__ import annotations

import argparse
import json
import logging
from pathlib import Path

import gcsfs
import pandas as pd
from unified_api_contracts.registry import LEAGUE_ENTITY_COVERAGE_ENTITIES
from unified_trading_library import resolve_bucket_name

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
logger = logging.getLogger("refresh_league_entity_coverage")

_MANIFEST_BLOB = "_index/availability_index.parquet"
_DEFAULT_UAC_JSON = (
    Path(__file__).resolve().parents[2]
    / "unified-api-contracts"
    / "unified_api_contracts"
    / "registry"
    / "data"
    / "sports_league_entity_coverage.json"
)


def build_coverage(df: pd.DataFrame) -> dict[str, list[str]]:
    """Build ``{ENTITY_UPPER: sorted([LEAGUE_UPPER, ...])}`` from captured rows."""
    dt = df["data_type"].astype("string").str.upper()
    entities = frozenset(LEAGUE_ENTITY_COVERAGE_ENTITIES)
    cap = df[(df["capture_status"].astype("string") == "captured") & dt.isin(entities)].copy()
    cap["e"] = cap["data_type"].astype("string").str.upper()
    cap["l"] = cap["league_id"].astype("string").str.upper()
    cap = cap[cap["l"].notna() & (cap["l"].str.len() > 0)]
    out: dict[str, set[str]] = {entity: set() for entity in sorted(entities)}
    for entity, lg in zip(cap["e"].tolist(), cap["l"].tolist(), strict=True):
        out.setdefault(str(entity), set()).add(str(lg))
    return {entity: sorted(leagues) for entity, leagues in sorted(out.items())}


def main(argv: list[str] | None = None) -> int:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--write", action="store_true", help="Overwrite the UAC JSON in place (then commit in UAC).")
    p.add_argument("--uac-json", type=Path, default=_DEFAULT_UAC_JSON, help="Path to the UAC coverage JSON.")
    args = p.parse_args(argv)

    bucket = resolve_bucket_name(cloud="gcp", kind="instruments-store", asset_group="sports")
    fs = gcsfs.GCSFileSystem()
    logger.info("Reading live _index gs://%s/%s", bucket, _MANIFEST_BLOB)
    with fs.open(f"{bucket}/{_MANIFEST_BLOB}", "rb") as fh:
        df = pd.read_parquet(fh, columns=["data_type", "league_id", "capture_status"])

    new_map = build_coverage(df)
    pairs = sum(len(v) for v in new_map.values())
    logger.info("Observed coverage: %d entities, %d (entity, league) pairs.", len(new_map), pairs)
    for entity in sorted(new_map):
        logger.info("  %s: %d covered leagues", entity, len(new_map[entity]))

    old_map: dict[str, list[str]] = {}
    if args.uac_json.exists():
        old_map = json.loads(args.uac_json.read_text())
    added = {e: sorted(set(new_map.get(e, [])) - set(old_map.get(e, []))) for e in new_map}
    added = {e: lg for e, lg in added.items() if lg}
    removed = {e: sorted(set(old_map.get(e, [])) - set(new_map.get(e, []))) for e in old_map}
    removed = {e: lg for e, lg in removed.items() if lg}
    if added:
        logger.info("New (entity, league) pairs vs committed map: %s", added)
    if removed:
        logger.info("Leagues absent from new scan (kept unless --write): %s", removed)
    if not added and not removed:
        logger.info("No drift vs committed coverage map.")

    if args.write:
        args.uac_json.write_text(json.dumps(new_map, indent=2, sort_keys=True) + "\n")
        logger.info("Wrote refreshed map -> %s (commit in UAC via quickmerge).", args.uac_json)
    else:
        logger.info("DRY RUN — committed UAC JSON untouched (use --write to overwrite).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
