"""
Instrument definitions for instruments-service.

Extracted from config.py per Task 1.1.1 (Issue #89), Task 1.1.2 (Issue #90).
DeFi protocol configs per Task 1.1.3 (Issue #91).

Ticker data (SP500, ETF, NASDAQ) is loaded from data/tickers.json (ISS-049).
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import cast

_DATA_DIR = Path(__file__).parent / "data"


def _load_tickers() -> dict[str, list[str] | str]:
    """Load ticker lists from the consolidated data/tickers.json file.

    Returns a dict with keys: sp500_tickers, etf_tickers, nasdaq_tickers,
    corporate_actions_start_date.
    """
    tickers_path = _DATA_DIR / "tickers.json"
    with open(tickers_path) as f:
        return cast(dict[str, list[str] | str], cast(object, json.load(f)))


_TICKERS = _load_tickers()

# Source: data/tickers.json (consolidated from ticker_lists.py, equity_definitions.py)
# Last updated: 2026-01-31
corporate_actions_start_date: str = cast(str, _TICKERS["corporate_actions_start_date"])

SP500_TICKERS: list[str] = cast(list[str], _TICKERS["sp500_tickers"])

ETF_TICKERS: list[str] = cast(list[str], _TICKERS["etf_tickers"])

NASDAQ_TICKERS: list[str] = cast(list[str], _TICKERS["nasdaq_tickers"])

# TRADFI venue mappings - Databento symbols to venues/datasets (Issue #90)
TRADFI_VENUE_MAPPINGS: list[dict[str, str | None]] = [
    {
        "symbol": "ES.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "ES",
    },
    {
        "symbol": "NQ.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NASDAQ100",
        "code": "NQ",
    },
    {
        "symbol": "RTY.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "RUSSELL2000",
        "code": "RTY",
    },
    {
        "symbol": "YM.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "DOW",
        "code": "YM",
    },
    {
        "symbol": "CL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CRUDE",
        "code": "CL",
    },
    {
        "symbol": "NG.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NATGAS",
        "code": "NG",
    },
    {
        "symbol": "RB.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GASOLINE",
        "code": "RB",
    },
    {
        "symbol": "HO.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "HEATINGOIL",
        "code": "HO",
    },
    {
        "symbol": "GC.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GOLD",
        "code": "GC",
    },
    {
        "symbol": "SI.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SILVER",
        "code": "SI",
    },
    {
        "symbol": "HG.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "COPPER",
        "code": "HG",
    },
    {
        "symbol": "PL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "PLATINUM",
        "code": "PL",
    },
    {
        "symbol": "ZC.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CORN",
        "code": "ZC",
    },
    {
        "symbol": "ZW.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "WHEAT",
        "code": "ZW",
    },
    {
        "symbol": "ZS.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYBEAN",
        "code": "ZS",
    },
    {
        "symbol": "ZM.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYMEAL",
        "code": "ZM",
    },
    {
        "symbol": "ZL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYOIL",
        "code": "ZL",
    },
    {
        "symbol": "ZB.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TBOND",
        "code": "ZB",
    },
    {
        "symbol": "ZN.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE10Y",
        "code": "ZN",
    },
    {
        "symbol": "ZF.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE5Y",
        "code": "ZF",
    },
    {
        "symbol": "ZT.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE2Y",
        "code": "ZT",
    },
    {
        "symbol": "6E.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "EUR",
        "code": "6E",
    },
    {
        "symbol": "6J.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "JPY",
        "code": "6J",
    },
    {
        "symbol": "6B.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GBP",
        "code": "6B",
    },
    {
        "symbol": "6C.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CAD",
        "code": "6C",
    },
    {
        "symbol": "6A.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "AUD",
        "code": "6A",
    },
    {
        "symbol": "6S.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CHF",
        "code": "6S",
    },
    {
        "symbol": "6L.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "BRL",
        "code": "6L",
    },
    {
        "symbol": "6N.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NZD",
        "code": "6N",
    },
    {
        "symbol": "6Z.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "ZAR",
        "code": "6Z",
    },
    {
        "symbol": "6M.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "MXN",
        "code": "6M",
    },
    # CME Livestock
    {
        "symbol": "LE.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "LIVECATTLE",
        "code": "LE",
    },
    {
        "symbol": "HE.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "LEANHOGS",
        "code": "HE",
    },
    # CFE (CBOE Futures Exchange) - Volatility
    {
        "symbol": "VX.FUT",
        "venue": "CFE",
        "type": "FUTURE",
        "dataset": "XCBF.MDP3",
        "stype": "parent",
        "base": "VIX",
        "code": "VX",
    },
    {
        "symbol": "ES.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "ES",
    },
    {
        "symbol": "NQ.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NASDAQ100",
        "code": "NQ",
    },
    {
        "symbol": "CL.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CRUDE",
        "code": "CL",
    },
    {
        "symbol": "GC.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GOLD",
        "code": "GC",
    },
    {
        "symbol": "EW1.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW1",
        "underlying": "ES",
    },
    {
        "symbol": "EW2.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW2",
        "underlying": "ES",
    },
    {
        "symbol": "EW3.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW3",
        "underlying": "ES",
    },
    {
        "symbol": "EW4.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW4",
        "underlying": "ES",
    },
    {
        "symbol": "CT.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COTTON",
        "code": "CT",
    },
    {
        "symbol": "CC.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COCOA",
        "code": "CC",
    },
    {
        "symbol": "KC.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COFFEE",
        "code": "KC",
    },
    {
        "symbol": "SB.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "SUGAR",
        "code": "SB",
    },
    {
        "symbol": "OJ.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "ORANGEJUICE",
        "code": "OJ",
    },
    {
        "symbol": "DX.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "DOLLARINDEX",
        "code": "DX",
    },
    {
        "symbol": "BRN.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "BRENT",
        "code": "BRN",
    },
    {
        "symbol": "G.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "GASOIL",
        "code": "G",
    },
    {
        "symbol": "T.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "WTI",
        "code": "T",
    },
]

# DeFi protocol configs (Issue #91)
# Maps canonical venue keys to (protocol, chain) for TheGraph/subgraph adapters
DEFI_VENUE_TO_PROTOCOL: dict[str, tuple[str, str | None]] = {
    "HYPERLIQUID": ("hyperliquid", None),
    "ASTER": ("aster", None),
    "UNISWAPV2-ETH": ("uniswap_v2", "ETHEREUM"),
    "UNISWAPV3-ETH": ("uniswap_v3", "ETHEREUM"),
    "UNISWAPV4-ETH": ("uniswap_v4", "ETHEREUM"),
    "CURVE-ETH": ("curve", "ETHEREUM"),
    "AAVE_V3_ETH": ("aave_v3", "ETHEREUM"),
    "ETHERFI": ("etherfi", "ETHEREUM"),
    "LIDO": ("lido", "ETHEREUM"),
    "MORPHO-ETHEREUM": ("morpho", "ETHEREUM"),
    "EULER-PLASMA": ("euler_plasma", None),
    "FLUID-PLASMA": ("fluid_plasma", None),
    "AAVE-PLASMA": ("aave_plasma", None),
    "ETHENA": ("ethena", "ETHEREUM"),
}

# All DeFi protocols to process when no venue filter is specified
DEFI_PROTOCOLS: list[tuple[str, str | None]] = [
    ("uniswap_v2", "ETHEREUM"),
    ("uniswap_v3", "ETHEREUM"),
    ("uniswap_v4", "ETHEREUM"),
    ("curve", "ETHEREUM"),
    ("balancer", "ETHEREUM"),
    ("aave_v3", "ETHEREUM"),
    ("etherfi", "ETHEREUM"),
    ("lido", "ETHEREUM"),
    ("morpho", "ETHEREUM"),
    ("euler_plasma", None),
    ("fluid_plasma", None),
    ("aave_plasma", None),
    ("hyperliquid", None),
    ("aster", None),
    ("ethena", "ETHEREUM"),
]

# Backward-compatible alias (Issue #90)
TRADFI_INSTRUMENTS_CONFIG: list[dict[str, str | None]] = TRADFI_VENUE_MAPPINGS
