"""
Instrument definitions for instruments-service.

Extracted from config.py per Task 1.1.1 (Issue #89), Task 1.1.2 (Issue #90).
DeFi protocol configs per Task 1.1.3 (Issue #91).
"""

# Source: Wikipedia S&P 500 list + manual ETF additions
# Last updated: 2026-01-31
corporate_actions_start_date: str = "2020-01-01"

SP500_TICKERS = [
    "AAPL",
    "ABBV",
    "ABT",
    "ACN",
    "ADBE",
    "ADI",
    "ADM",
    "ADP",
    "ADSK",
    "AEE",
    "AEP",
    "AES",
    "AFL",
    "AIG",
    "AIZ",
    "AJG",
    "AKAM",
    "ALB",
    "ALGN",
    "ALL",
    "ALLE",
    "AMAT",
    "AMCR",
    "AMD",
    "AME",
    "AMGN",
    "AMP",
    "AMT",
    "AMZN",
    "ANET",
    "ANSS",
    "AON",
    "AOS",
    "APA",
    "APD",
    "APH",
    "APTV",
    "ARE",
    "ATO",
    "AVB",
    "AVGO",
    "AVY",
    "AWK",
    "AXON",
    "AXP",
    "AZO",
    "BA",
    "BAC",
    "BALL",
    "BAX",
    "BBWI",
    "BBY",
    "BDX",
    "BEN",
    "BF.B",
    "BG",
    "BIIB",
    "BIO",
    "BK",
    "BKNG",
    "BKR",
    "BLDR",
    "BLK",
    "BMY",
    "BR",
    "BRK.B",
    "BRO",
    "BSX",
    "BWA",
    "BX",
    "BXP",
    "C",
    "CAG",
    "CAH",
    "CARR",
    "CAT",
    "CB",
    "CBOE",
    "CBRE",
    "CCI",
    "CCL",
    "CDNS",
    "CDW",
    "CE",
    "CEG",
    "CF",
    "CFG",
    "CHD",
    "CHRW",
    "CHTR",
    "CI",
    "CINF",
    "CL",
    "CLX",
    "CMA",
    "CMCSA",
    "CME",
    "CMG",
    "CMI",
    "CMS",
    "CNC",
    "CNP",
    "COF",
    "COO",
    "COP",
    "COR",
    "COST",
    "CPAY",
    "CPB",
    "CPRT",
    "CPT",
    "CRL",
    "CRM",
    "CSCO",
    "CSGP",
    "CSX",
    "CTAS",
    "CTLT",
    "CTRA",
    "CTSH",
    "CTVA",
    "CVS",
    "CVX",
    "CZR",
    "D",
    "DAL",
    "DAY",
    "DD",
    "DE",
    "DECK",
    "DFS",
    "DG",
    "DGX",
    "DHI",
    "DHR",
    "DIS",
    "DLR",
    "DLTR",
    "DOC",
    "DOV",
    "DOW",
    "DPZ",
    "DRI",
    "DTE",
    "DUK",
    "DVA",
    "DVN",
    "DXCM",
    "EA",
    "EBAY",
    "ECL",
    "ED",
    "EFX",
    "EG",
    "EIX",
    "EL",
    "ELV",
    "EMN",
    "EMR",
    "ENPH",
    "EOG",
    "EPAM",
    "EQIX",
    "EQR",
    "EQT",
    "ES",
    "ESS",
    "ETN",
    "ETR",
    "EVRG",
    "EW",
    "EXC",
    "EXPD",
    "EXPE",
    "EXR",
    "F",
    "FANG",
    "FAST",
    "FCX",
    "FDS",
    "FDX",
    "FE",
    "FFIV",
    "FI",
    "FICO",
    "FIS",
    "FITB",
    "FLT",
    "FMC",
    "FOX",
    "FOXA",
    "FRT",
    "FSLR",
    "FTNT",
    "FTV",
    "GD",
    "GDDY",
    "GE",
    "GEHC",
    "GEN",
    "GEV",
    "GILD",
    "GIS",
    "GL",
    "GLW",
    "GM",
    "GNRC",
    "GOOG",
    "GOOGL",
    "GPC",
    "GPN",
    "GRMN",
    "GS",
    "GWW",
    "HAL",
    "HAS",
    "HBAN",
    "HCA",
    "HD",
    "HES",
    "HIG",
    "HII",
    "HLT",
    "HOLX",
    "HON",
    "HPE",
    "HPQ",
    "HRL",
    "HSIC",
    "HST",
    "HSY",
    "HUBB",
    "HUM",
    "HWM",
    "IBM",
    "ICE",
    "IDXX",
    "IEX",
    "IFF",
    "INCY",
    "INTC",
    "INTU",
    "INVH",
    "IP",
    "IPG",
    "IQV",
    "IR",
    "IRM",
    "ISRG",
    "IT",
    "ITW",
    "IVZ",
    "J",
    "JBHT",
    "JBL",
    "JCI",
    "JKHY",
    "JNJ",
    "JNPR",
    "JPM",
    "K",
    "KDP",
    "KEY",
    "KEYS",
    "KHC",
    "KIM",
    "KKR",
    "KLAC",
    "KMB",
    "KMI",
    "KMX",
    "KO",
    "KR",
    "KVUE",
    "L",
    "LDOS",
    "LEN",
    "LH",
    "LHX",
    "LIN",
    "LKQ",
    "LLY",
    "LMT",
    "LNT",
    "LOW",
    "LRCX",
    "LULU",
    "LUV",
    "LVS",
    "LW",
    "LYB",
    "LYV",
    "MA",
    "MAA",
    "MAR",
    "MAS",
    "MCD",
    "MCHP",
    "MCK",
    "MCO",
    "MDLZ",
    "MDT",
    "MET",
    "META",
    "MGM",
    "MHK",
    "MKC",
    "MKTX",
    "MLM",
    "MMC",
    "MMM",
    "MNST",
    "MO",
    "MOH",
    "MOS",
    "MPC",
    "MPWR",
    "MRK",
    "MRNA",
    "MRO",
    "MS",
    "MSCI",
    "MSFT",
    "MSI",
    "MTB",
    "MTCH",
    "MTD",
    "MU",
    "NCLH",
    "NDAQ",
    "NDSN",
    "NEE",
    "NEM",
    "NFLX",
    "NI",
    "NKE",
    "NOC",
    "NOW",
    "NRG",
    "NSC",
    "NTAP",
    "NTRS",
    "NUE",
    "NVDA",
    "NVR",
    "NWS",
    "NWSA",
    "NXPI",
    "O",
    "ODFL",
    "OKE",
    "OMC",
    "ON",
    "ORCL",
    "ORLY",
    "OTIS",
    "OXY",
    "PANW",
    "PARA",
    "PAYC",
    "PAYX",
    "PCAR",
    "PCG",
    "PEG",
    "PEP",
    "PFE",
    "PFG",
    "PG",
    "PGR",
    "PH",
    "PHM",
    "PKG",
    "PLD",
    "PLTR",
    "PM",
    "PNC",
    "PNR",
    "PNW",
    "PODD",
    "POOL",
    "PPG",
    "PPL",
    "PRU",
    "PSA",
    "PSX",
    "PTC",
    "PWR",
    "PYPL",
    "QCOM",
    "QRVO",
    "RCL",
    "REG",
    "REGN",
    "RF",
    "RJF",
    "RL",
    "RMD",
    "ROK",
    "ROL",
    "ROP",
    "ROST",
    "RSG",
    "RTX",
    "RVTY",
    "SBAC",
    "SBUX",
    "SCHW",
    "SHW",
    "SJM",
    "SLB",
    "SMCI",
    "SNA",
    "SNPS",
    "SO",
    "SOLV",
    "SPG",
    "SPGI",
    "SRE",
    "STE",
    "STLD",
    "STT",
    "STX",
    "STZ",
    "SW",
    "SWK",
    "SWKS",
    "SYF",
    "SYK",
    "SYY",
    "T",
    "TAP",
    "TDG",
    "TDY",
    "TECH",
    "TEL",
    "TER",
    "TFC",
    "TFX",
    "TGT",
    "TJX",
    "TMO",
    "TMUS",
    "TPR",
    "TRGP",
    "TRMB",
    "TROW",
    "TRV",
    "TSCO",
    "TSLA",
    "TSN",
    "TT",
    "TTWO",
    "TXN",
    "TXT",
    "TYL",
    "UAL",
    "UBER",
    "UDR",
    "UHS",
    "ULTA",
    "UNH",
    "UNP",
    "UPS",
    "URI",
    "USB",
    "V",
    "VICI",
    "VLO",
    "VLTO",
    "VMC",
    "VRSK",
    "VRSN",
    "VRTX",
    "VST",
    "VTR",
    "VTRS",
    "VZ",
    "WAB",
    "WAT",
    "WBA",
    "WBD",
    "WDC",
    "WEC",
    "WELL",
    "WFC",
    "WM",
    "WMB",
    "WMT",
    "WRB",
    "WST",
    "WTW",
    "WY",
    "WYNN",
    "XEL",
    "XOM",
    "XYL",
    "YUM",
    "ZBH",
    "ZBRA",
    "ZTS",
]

# ETF tickers including Bitcoin ETFs
ETF_TICKERS = [
    "SPY",
    "QQQ",
    "IVV",
    "VOO",
    "VTI",
    "DIA",
    "IWM",
    "IBIT",
    "FBTC",
    "ARKB",
    "GBTC",
    "BITO",  # Bitcoin ETFs
    "GLD",
    "SLV",
    "USO",  # Commodity ETFs
    "XLF",
    "XLE",
    "XLK",
    "XLV",  # Sector ETFs
]

# NASDAQ-listed tickers (subset of S&P 500 that trade on NASDAQ vs NYSE)
NASDAQ_TICKERS = [
    "AAPL",
    "ADBE",
    "ADI",
    "ADP",
    "ADSK",
    "AEP",
    "ALGN",
    "AMAT",
    "AMD",
    "AMGN",
    "AMZN",
    "ANSS",
    "ASML",
    "AVGO",
    "AZN",
    "BIDU",
    "BIIB",
    "BKNG",
    "CDNS",
    "CDW",
    "CEG",
    "CHTR",
    "CMCSA",
    "COST",
    "CPRT",
    "CRWD",
    "CSCO",
    "CSGP",
    "CSX",
    "CTAS",
    "CTSH",
    "DDOG",
    "DLTR",
    "DXCM",
    "EA",
    "EBAY",
    "ENPH",
    "EXC",
    "FANG",
    "FAST",
    "FTNT",
    "GEHC",
    "GFS",
    "GILD",
    "GOOG",
    "GOOGL",
    "HON",
    "IDXX",
    "ILMN",
    "INTC",
    "INTU",
    "ISRG",
    "JD",
    "KDP",
    "KHC",
    "KLAC",
    "LRCX",
    "LULU",
    "MAR",
    "MCHP",
    "MDLZ",
    "MELI",
    "META",
    "MNST",
    "MRNA",
    "MRVL",
    "MSFT",
    "MU",
    "NFLX",
    "NVDA",
    "NXPI",
    "ODFL",
    "ON",
    "ORLY",
    "PANW",
    "PAYX",
    "PCAR",
    "PDD",
    "PEP",
    "PYPL",
    "QCOM",
    "REGN",
    "RIVN",
    "ROST",
    "SBUX",
    "SIRI",
    "SNPS",
    "TEAM",
    "TMUS",
    "TSLA",
    "TTD",
    "TXN",
    "VRSK",
    "VRTX",
    "WBA",
    "WDAY",
    "XEL",
    "ZM",
    "ZS",
    # Bitcoin ETFs also trade on NASDAQ
    "IBIT",
    "FBTC",
    "ARKB",
]

# TRADFI venue mappings - Databento symbols to venues/datasets (Issue #90)
TRADFI_VENUE_MAPPINGS: list[dict[str, str | None]] = [
    {
        "symbol": "ES.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "ES",
    },
    {
        "symbol": "NQ.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NASDAQ100",
        "code": "NQ",
    },
    {
        "symbol": "RTY.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "RUSSELL2000",
        "code": "RTY",
    },
    {
        "symbol": "YM.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "DOW",
        "code": "YM",
    },
    {
        "symbol": "CL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CRUDE",
        "code": "CL",
    },
    {
        "symbol": "NG.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NATGAS",
        "code": "NG",
    },
    {
        "symbol": "RB.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GASOLINE",
        "code": "RB",
    },
    {
        "symbol": "HO.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "HEATINGOIL",
        "code": "HO",
    },
    {
        "symbol": "GC.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GOLD",
        "code": "GC",
    },
    {
        "symbol": "SI.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SILVER",
        "code": "SI",
    },
    {
        "symbol": "HG.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "COPPER",
        "code": "HG",
    },
    {
        "symbol": "PL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "PLATINUM",
        "code": "PL",
    },
    {
        "symbol": "ZC.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CORN",
        "code": "ZC",
    },
    {
        "symbol": "ZW.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "WHEAT",
        "code": "ZW",
    },
    {
        "symbol": "ZS.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYBEAN",
        "code": "ZS",
    },
    {
        "symbol": "ZM.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYMEAL",
        "code": "ZM",
    },
    {
        "symbol": "ZL.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SOYOIL",
        "code": "ZL",
    },
    {
        "symbol": "ZB.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TBOND",
        "code": "ZB",
    },
    {
        "symbol": "ZN.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE10Y",
        "code": "ZN",
    },
    {
        "symbol": "ZF.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE5Y",
        "code": "ZF",
    },
    {
        "symbol": "ZT.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "TNOTE2Y",
        "code": "ZT",
    },
    {
        "symbol": "6E.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "EUR",
        "code": "6E",
    },
    {
        "symbol": "6J.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "JPY",
        "code": "6J",
    },
    {
        "symbol": "6B.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GBP",
        "code": "6B",
    },
    {
        "symbol": "6C.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CAD",
        "code": "6C",
    },
    {
        "symbol": "6A.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "AUD",
        "code": "6A",
    },
    {
        "symbol": "6S.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CHF",
        "code": "6S",
    },
    {
        "symbol": "6L.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "BRL",
        "code": "6L",
    },
    {
        "symbol": "6N.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NZD",
        "code": "6N",
    },
    {
        "symbol": "6Z.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "ZAR",
        "code": "6Z",
    },
    {
        "symbol": "6M.FUT",
        "venue": "CME",
        "type": "FUTURE",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "MXN",
        "code": "6M",
    },
    {
        "symbol": "ES.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "ES",
    },
    {
        "symbol": "NQ.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "NASDAQ100",
        "code": "NQ",
    },
    {
        "symbol": "CL.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "CRUDE",
        "code": "CL",
    },
    {
        "symbol": "GC.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "GOLD",
        "code": "GC",
    },
    {
        "symbol": "EW1.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW1",
        "underlying": "ES",
    },
    {
        "symbol": "EW2.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW2",
        "underlying": "ES",
    },
    {
        "symbol": "EW3.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW3",
        "underlying": "ES",
    },
    {
        "symbol": "EW4.OPT",
        "venue": "CME",
        "type": "OPTION",
        "dataset": "GLBX.MDP3",
        "stype": "parent",
        "base": "SP500",
        "code": "EW4",
        "underlying": "ES",
    },
    {
        "symbol": "CT.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COTTON",
        "code": "CT",
    },
    {
        "symbol": "CC.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COCOA",
        "code": "CC",
    },
    {
        "symbol": "KC.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "COFFEE",
        "code": "KC",
    },
    {
        "symbol": "SB.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "SUGAR",
        "code": "SB",
    },
    {
        "symbol": "OJ.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "ORANGEJUICE",
        "code": "OJ",
    },
    {
        "symbol": "DX.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFUS.IMPACT",
        "stype": "parent",
        "base": "DOLLARINDEX",
        "code": "DX",
    },
    {
        "symbol": "BRN.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "BRENT",
        "code": "BRN",
    },
    {
        "symbol": "G.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "GASOIL",
        "code": "G",
    },
    {
        "symbol": "T.FUT",
        "venue": "ICE",
        "type": "FUTURE",
        "dataset": "IFEU.IMPACT",
        "stype": "parent",
        "base": "WTI",
        "code": "T",
    },
]

# DeFi protocol configs (Issue #91)
# Maps canonical venue keys to (protocol, chain) for TheGraph/subgraph adapters
DEFI_VENUE_TO_PROTOCOL: dict[str, tuple[str, str | None]] = {
    "HYPERLIQUID": ("hyperliquid", None),
    "ASTER": ("aster", None),
    "UNISWAPV2-ETH": ("uniswap_v2", "ETHEREUM"),
    "UNISWAPV3-ETH": ("uniswap_v3", "ETHEREUM"),
    "UNISWAPV4-ETH": ("uniswap_v4", "ETHEREUM"),
    "CURVE-ETH": ("curve", "ETHEREUM"),
    "AAVE_V3_ETH": ("aave_v3", "ETHEREUM"),
    "ETHERFI": ("etherfi", "ETHEREUM"),
    "LIDO": ("lido", "ETHEREUM"),
    "MORPHO-ETHEREUM": ("morpho", "ETHEREUM"),
    "EULER-PLASMA": ("euler_plasma", None),
    "FLUID-PLASMA": ("fluid_plasma", None),
    "AAVE-PLASMA": ("aave_plasma", None),
    "ETHENA": ("ethena", "ETHEREUM"),
}

# All DeFi protocols to process when no venue filter is specified
DEFI_PROTOCOLS: list[tuple[str, str | None]] = [
    ("uniswap_v2", "ETHEREUM"),
    ("uniswap_v3", "ETHEREUM"),
    ("uniswap_v4", "ETHEREUM"),
    ("curve", "ETHEREUM"),
    ("balancer", "ETHEREUM"),
    ("aave_v3", "ETHEREUM"),
    ("etherfi", "ETHEREUM"),
    ("lido", "ETHEREUM"),
    ("morpho", "ETHEREUM"),
    ("euler_plasma", None),
    ("fluid_plasma", None),
    ("aave_plasma", None),
    ("hyperliquid", None),
    ("aster", None),
    ("ethena", "ETHEREUM"),
]

# Backward-compatible alias (Issue #90)
TRADFI_INSTRUMENTS_CONFIG: list[dict[str, str | None]] = TRADFI_VENUE_MAPPINGS
