"""Bundesliga team/stadium mapping data.

Extracted from team_mapping_data.py for file size compliance.
See team_mapping_data.py for EPL mappings.
"""

from __future__ import annotations

BUNDESLIGA_TEAM_MAPPINGS: list[dict[str, str | int | None | list[str]]] = [
    {
        "canonical_team_id": "ARMINIA_BIELEFELD",
        "display_name": "Arminia Bielefeld",
        "api_football_id": None,
        "aliases": [
            "ARMINIA BIELEFELD",
            "BIELEFELD",
            "ARMINIA",
            "Bielefeld",
            "Arminia",
        ],
    },
    {
        "canonical_team_id": "AUGSBURG",
        "display_name": "Augsburg",
        "api_football_id": None,
        "aliases": [
            "AUGSBURG",
            "FC AUGSBURG",
            "FC Augsburg",
        ],
    },
    {
        "canonical_team_id": "BAYERN",
        "display_name": "Bayern Munich",
        "api_football_id": 157,
        "aliases": [
            "BAYERN",
            "BAYERN MUNICH",
            "FC BAYERN MUNICH",
            "BAYERN MUNCHEN",
            "Bayern",
            "FC Bayern Munich",
            "Bayern Munchen",
            "Bayern München",
        ],
    },
    {
        "canonical_team_id": "BOCHUM",
        "display_name": "Bochum",
        "api_football_id": 176,
        "aliases": [
            "BOCHUM",
            "VFL BOCHUM",
            "VfL Bochum",
            "Vfl Bochum",
        ],
    },
    {
        "canonical_team_id": "DORTMUND",
        "display_name": "Borussia Dortmund",
        "api_football_id": None,
        "aliases": [
            "BORUSSIA DORTMUND",
            "DORTMUND",
            "BVB",
            "Dortmund",
        ],
    },
    {
        "canonical_team_id": "MGLADBACH",
        "display_name": "Borussia Monchengladbach",
        "api_football_id": 163,
        "aliases": [
            "BORUSSIA MONCHENGLADBACH",
            "BORUSSIA M'GLADBACH",
            "MGLADBACH",
            "MONCHENGLADBACH",
            "M'GLADBACH",
            "Borussia M.Gladbach",
            "Borussia Mönchengladbach",
            "Monchengladbach",
        ],
    },
    {
        "canonical_team_id": "COLOGNE",
        "display_name": "FC Cologne",
        "api_football_id": 192,
        "aliases": [
            "COLOGNE",
            "FC KOLN",
            "FC COLOGNE",
            "KOLN",
            "Koln",
            "FC Koln",
            "1.FC Köln",
            "1. FC Köln",
        ],
    },
    {
        "canonical_team_id": "DARMSTADT",
        "display_name": "Darmstadt",
        "api_football_id": None,
        "aliases": [
            "DARMSTADT",
            "DARMSTADT 98",
            "SV Darmstadt 98",
            "Darmstadt 98",
        ],
    },
    {
        "canonical_team_id": "FRANKFURT",
        "display_name": "Eintracht Frankfurt",
        "api_football_id": None,
        "aliases": [
            "EINTRACHT FRANKFURT",
            "FRANKFURT",
            "Frankfurt",
        ],
    },
    {
        "canonical_team_id": "FREIBURG",
        "display_name": "Freiburg",
        "api_football_id": None,
        "aliases": [
            "FREIBURG",
            "SC FREIBURG",
            "SC Freiburg",
        ],
    },
    {
        "canonical_team_id": "GREUTHER_FURTH",
        "display_name": "Greuther Furth",
        "api_football_id": 178,
        "aliases": [
            "GREUTHER FURTH",
            "GREUTHER FÜRTH",
            "SpVgg Greuther Fürth",
            "SpVgg Greuther Furth",
            "Greuther Fuerth",
        ],
    },
    {
        "canonical_team_id": "HAMBURG",
        "display_name": "Hamburger SV",
        "api_football_id": None,
        "aliases": [
            "HAMBURGER SV",
            "HAMBURG",
            "HSV",
            "Hamburg",
        ],
    },
    {
        "canonical_team_id": "HANNOVER",
        "display_name": "Hannover 96",
        "api_football_id": None,
        "aliases": [
            "HANNOVER",
            "HANNOVER 96",
            "Hannover",
        ],
    },
    {
        "canonical_team_id": "HERTHA",
        "display_name": "Hertha Berlin",
        "api_football_id": 159,
        "aliases": [
            "HERTHA BERLIN",
            "HERTHA",
            "HERTHA BSC",
            "Hertha BSC",
            "Hertha",
        ],
    },
    {
        "canonical_team_id": "HOFFENHEIM",
        "display_name": "Hoffenheim",
        "api_football_id": None,
        "aliases": [
            "HOFFENHEIM",
            "TSG HOFFENHEIM",
            "TSG Hoffenheim",
            "1899 Hoffenheim",
        ],
    },
    {
        "canonical_team_id": "HEIDENHEIM",
        "display_name": "Heidenheim",
        "api_football_id": 180,
        "aliases": [
            "HEIDENHEIM",
            "FC HEIDENHEIM",
            "FC Heidenheim",
            "1. FC Heidenheim",
        ],
    },
    {
        "canonical_team_id": "HOLSTEIN_KIEL",
        "display_name": "Holstein Kiel",
        "api_football_id": None,
        "aliases": [
            "HOLSTEIN KIEL",
            "KIEL",
            "Kiel",
        ],
    },
    {
        "canonical_team_id": "KAISERSLAUTERN",
        "display_name": "Kaiserslautern",
        "api_football_id": 745,
        "aliases": [
            "KAISERSLAUTERN",
            "FC KAISERSLAUTERN",
            "FC Kaiserslautern",
            "1. FC Kaiserslautern",
        ],
    },
    {
        "canonical_team_id": "KARLSRUHE",
        "display_name": "Karlsruhe",
        "api_football_id": None,
        "aliases": [
            "KARLSRUHE",
            "KARLSRUHER SC",
            "Karlsruher SC",
        ],
    },
    {
        "canonical_team_id": "LEVERKUSEN",
        "display_name": "Bayer Leverkusen",
        "api_football_id": None,
        "aliases": [
            "LEVERKUSEN",
            "BAYER LEVERKUSEN",
            "Leverkusen",
        ],
    },
    {
        "canonical_team_id": "MAINZ",
        "display_name": "Mainz",
        "api_football_id": None,
        "aliases": [
            "MAINZ",
            "MAINZ 05",
            "FSV MAINZ 05",
            "Mainz 05",
            "FSV Mainz 05",
        ],
    },
    {
        "canonical_team_id": "PADERBORN",
        "display_name": "Paderborn",
        "api_football_id": None,
        "aliases": [
            "PADERBORN",
            "SC PADERBORN",
            "SC Paderborn",
            "SC Paderborn 07",
        ],
    },
    {
        "canonical_team_id": "LEIPZIG",
        "display_name": "RB Leipzig",
        "api_football_id": None,
        "aliases": [
            "LEIPZIG",
            "RB LEIPZIG",
            "Leipzig",
            "RasenBallsport Leipzig",
        ],
    },
    {
        "canonical_team_id": "SCHALKE",
        "display_name": "Schalke 04",
        "api_football_id": None,
        "aliases": [
            "SCHALKE",
            "SCHALKE 04",
            "FC SCHALKE 04",
            "FC Schalke 04",
        ],
    },
    {
        "canonical_team_id": "ST_PAULI",
        "display_name": "FC St. Pauli",
        "api_football_id": None,
        "aliases": [
            "ST PAULI",
            "ST. PAULI",
            "FC ST PAULI",
            "St Pauli",
            "St. Pauli",
            "FC St Pauli",
        ],
    },
    {
        "canonical_team_id": "STUTTGART",
        "display_name": "VfB Stuttgart",
        "api_football_id": None,
        "aliases": [
            "STUTTGART",
            "VFB STUTTGART",
            "Stuttgart",
        ],
    },
    {
        "canonical_team_id": "UNION_BERLIN",
        "display_name": "Union Berlin",
        "api_football_id": None,
        "aliases": [
            "UNION BERLIN",
            "UNION",
            "FC UNION BERLIN",
            "FC Union Berlin",
        ],
    },
    {
        "canonical_team_id": "WERDER_BREMEN",
        "display_name": "Werder Bremen",
        "api_football_id": None,
        "aliases": [
            "WERDER BREMEN",
            "BREMEN",
            "SV WERDER BREMEN",
            "Bremen",
            "SV Werder Bremen",
        ],
    },
    {
        "canonical_team_id": "WOLFSBURG",
        "display_name": "Wolfsburg",
        "api_football_id": None,
        "aliases": [
            "WOLFSBURG",
            "VFL WOLFSBURG",
            "VfL Wolfsburg",
        ],
    },
    # -- Historical Bundesliga teams (2010-2019, relegated/not current) --
    {
        "canonical_team_id": "NURNBERG",
        "display_name": "FC Nurnberg",
        "api_football_id": 171,
        "aliases": [
            "1. FC Nürnberg",
            "Nurnberg",
            "Nuernberg",
        ],
    },
    {
        "canonical_team_id": "FORTUNA_DUSSELDORF",
        "display_name": "Fortuna Dusseldorf",
        "api_football_id": 158,
        "aliases": [
            "Fortuna Düsseldorf",
            "Fortuna Duesseldorf",
        ],
    },
    {
        "canonical_team_id": "BRAUNSCHWEIG",
        "display_name": "Eintracht Braunschweig",
        "api_football_id": None,
        "aliases": [
            "Braunschweig",
        ],
    },
    {
        "canonical_team_id": "INGOLSTADT",
        "display_name": "FC Ingolstadt",
        "api_football_id": None,
        "aliases": [
            "FC Ingolstadt 04",
            "Ingolstadt",
        ],
    },
    {
        "canonical_team_id": "ELVERSBERG",
        "display_name": "SV Elversberg",
        "api_football_id": None,
        "aliases": [
            "Elversberg",
        ],
    },
]


# ---------------------------------------------------------------------------
# Stadium mappings — API-Football raw name -> canonical name
# Sourced from legacy API_FOOTBALL_TO_CANONICAL_STADIUMS
# ---------------------------------------------------------------------------

STADIUM_MAPPINGS: dict[str, str] = {
    # Premier League Stadiums
    "Old Trafford": "OLD_TRAFFORD",
    "St. James' Park": "ST_JAMES_PARK",
    "Craven Cottage": "CRAVEN_COTTAGE",
    "Molineux Stadium": "MOLINEUX",
    "Anfield": "ANFIELD",
    "Emirates Stadium": "EMIRATES",
    "Hill Dickinson Stadium": "GOODISON_PARK",
    "Tottenham Hotspur Stadium": "TOTTENHAM_HOTSPUR_STADIUM",
    "London Stadium": "LONDON_STADIUM",
    "Stamford Bridge": "STAMFORD_BRIDGE",
    "Etihad Stadium": "ETIHAD",
    "St Andrew's Stadium": "ST_ANDREWS",
    "The Hawthorns": "THE_HAWTHORNS",
    "DW Stadium": "DW_STADIUM",
    "Villa Park": "VILLA_PARK",
    "Ewood Park": "EWOOD_PARK",
    "Toughsheet Community Stadium": "UNIVERSITY_OF_BOLTON_STADIUM",
    "bet365 Stadium": "BET365_STADIUM",
    "Stadium of Light": "STADIUM_OF_LIGHT",
    "Bloomfield Road": "BLOOMFIELD_ROAD",
    "Carrow Road": "CARROW_ROAD",
    "MATRADE Loftus Road": "LOFTUS_ROAD",
    "Swansea.com Stadium": "SWANSEA_STADIUM",
    "St. Mary's Stadium": "ST_MARYS",
    "Select Car Leasing Stadium": "MADEJSKI_STADIUM",
    "Cardiff City Stadium": "CARDIFF_CITY_STADIUM",
    "Selhurst Park": "SELHURST_PARK",
    "The MKM Stadium": "MKM_STADIUM",
    "Turf Moor": "TURF_MOOR",
    "King Power Stadium": "KING_POWER_STADIUM",
    "Vitality Stadium": "VITALITY_STADIUM",
    "Vicarage Road": "VICARAGE_ROAD",
    "Riverside Stadium": "RIVERSIDE_STADIUM",
    "John Smith's Stadium": "JOHN_SMITHS_STADIUM",
    "American Express Stadium": "AMEX_STADIUM",
    "Bramall Lane": "BRAMALL_LANE",
    "Elland Road": "ELLAND_ROAD",
    "Gtech Community Stadium": "GTECH_COMMUNITY_STADIUM",
    "The City Ground": "CITY_GROUND",
    "Kenilworth Road": "KENILWORTH_ROAD",
    "Portman Road": "PORTMAN_ROAD",
    # Bundesliga Stadiums
    "Fußball Arena München": "ALLIANZ_ARENA",
    "Europa-Park Stadion": "EUROPA_PARK_STADION",
    "Volkswagen Arena": "VOLKSWAGEN_ARENA",
    "wohninvest WESERSTADION": "WESERSTADION",
    "BORUSSIA-PARK": "BORUSSIA_PARK",
    "MEWA ARENA": "MEWA_ARENA",
    "BVB Stadion Dortmund": "SIGNAL_IDUNA_PARK",
    "Heinz von Heiden-Arena": "HEINZ_VON_HEIDEN_ARENA",
    "PreZero Arena": "PREZERO_ARENA",
    "BayArena": "BAYARENA",
    "Frankfurt Arena": "DEUTSCHE_BANK_PARK",
    "Max-Morlock-Stadion": "MAX_MORLOCK_STADION",
    "Stuttgart Arena": "MERCEDES_BENZ_ARENA",
    "Arena AufSchalke": "VELTINS_ARENA",
    "Volksparkstadion": "VOLKSPARKSTADION",
    "Millerntor-Stadion": "MILLERNTOR_STADION",
    "Cologne Stadium": "RHEINENERGIESTADION",
    "Fritz-Walter-Stadion": "FRITZ_WALTER_STADION",
    "Olympiastadion Berlin": "OLYMPIASTADION_BERLIN",
    "WWK Arena": "WWK_ARENA",
    "Düsseldorf Arena": "MERKUR_SPIEL_ARENA",
    "Sportpark Ronhof Thomas Sommer": "SPORTPARK_RONHOF",
    "Eintracht-Stadion": "EINTRACHT_STADION",
    "Home Deluxe Arena": "HOME_DELUXE_ARENA",
    "Merck-Stadion am Böllenfalltor": "MERCK_STADION",
    "Audi-Sportpark": "AUDI_SPORTPARK",
    "Leipzig Stadium": "RED_BULL_ARENA",
    "Stadion An der Alten Försterei": "AN_DER_ALTEN_FORSTEREI",
    "Voith-Arena": "VOITH_ARENA",
    "SchücoArena": "SCHUCO_ARENA",
    "Holstein-Stadion": "HOLSTEIN_STADION",
    "Vonovia Ruhrstadion": "VONOVIA_RUHRSTADION",
    "URSAPHARM-Arena an der Kaiserlinde": "URSAPHARM_ARENA",
}


# ---------------------------------------------------------------------------
# Team name corrections — API-Football team_id -> corrected display name
# Sourced from legacy team_name_changes.py (44 entries)
# ---------------------------------------------------------------------------

TEAM_NAME_CORRECTIONS: dict[int, str] = {
    111: "Le Havre",
    157: "Bayern Munich",
    158: "Fortuna Dusseldorf",
    159: "Hertha Berlin",
    163: "Borussia Monchengladbach",
    171: "FC Nurnberg",
    176: "Vfl Bochum",
    177: "Jahn Regensburg",
    178: "SpVgg Greuther Furth",
    179: "FC Magdeburg",
    180: "FC Heidenheim",
    190: "Erzgebirge AUE",
    192: "FC Koln",
    372: "IF Elfsborg",
    397: "FC Midtjylland",
    553: "Olympiakos Piraeus",
    596: "Zenit Saint Petersburg",
    597: "Lokomotiv Moscow",
    621: "FC Krasnodar",
    632: "Universitatea Craiova",
    745: "FC Kaiserslautern",
    784: "FC Wurzburger Kickers",
    870: "Calcio Padova",
    895: "Como",
    1079: "Krylia Sovetov",
    1080: "FC Orenburg",
    1081: "TOM Tomsk",
    1085: "Akhmat Grozny",
    1088: "Dynamo Moscow",
    1313: "Preussen Munster",
    1324: "VfL Osnabruck",
    1325: "Carl Zeiss Jena",
    1620: "FC Viktoria Koln",
    1621: "Rot-weiss Essen",
    1625: "VfB Lubeck",
    1630: "Bremer SV",
    1639: "FC Saarbrucken",
    1652: "SSV Ulm 1846",
    1993: "Fakel Voronezh",
    2012: "PFC Sochi",
    6813: "Dinamo Makhachkala",
    10137: "Nuova Cosenza",
}
